//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportCompany.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransportCompany.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///INSERT INTO [Routes] VALUES
        ///(N&apos;Пермь — Новосибирск&apos;,1440,20),
        ///(N&apos;Пермь — Бердск&apos;,2009,25),
        ///(N&apos;Пермь — Кемерово&apos;,2289,28),
        ///(N&apos;Пермь — Новокузнецк&apos;,1440,20),
        ///(N&apos;Пермь — Барнаул&apos;,2200,28),
        ///(N&apos;Пермь — Бийск&apos;,2329,29),
        ///(N&apos;Пермь — Абакан&apos;,2861,50),
        ///(N&apos;Пермь — Омск&apos;,1324,17),
        ///(N&apos;Пермь — Тюмень&apos;,689,10),
        ///(N&apos;Пермь — Красноярск&apos;,2750,35),
        ///(N&apos;Пермь — Сургут&apos;,1467,19),
        ///(N&apos;Пермь — Нижневартовск&apos;,1682,21),
        ///(N&apos;Пермь — Ханты-Мансийск&apos;,1175,15),
        ///(N&apos;Пермь — Ноябрьск&apos;,1774,22),
        ///(N&apos;Пермь — Нижний Новгород&apos;,970 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string seed {
            get {
                return ResourceManager.GetString("seed", resourceCulture);
            }
        }
    }
}
